version: '3'
services:
  server:
    image: node:16.13.0
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=motivate
      - DB_CONNECTION=mongodb://george:motivatepass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=george
      - MONGO_INITDB_DATABASE=motivate
      - MONGO_INITDB_ROOT_PASSWORD=motivatepass
volumes:
  dbdata: